# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- experiment/v13

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        amd64:
          ARCH: 'amd64'
        arm64:
          ARCH: 'arm64'
    steps:
    - script: |
        echo "##vso[task.setvariable variable=dockerBuildContext]$(Build.SourcesDirectory)"
      displayName: 'Set Docker build context'
    - script: |
        echo "##vso[task.setvariable variable=dockerBuildArgs]--build-arg ARCH=$(ARCH)"
      displayName: 'Set Docker build arguments'
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '23.0.3'
    - script: |
        echo '{"experimental": "enabled"}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        docker version
        docker buildx create --name mybuilder --driver docker-container --use
      displayName: 'Enable buildx and create build context'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
        arguments: $(dockerBuildArgs)
        buildContext: $(dockerBuildContext)
        additionalImageTags: $(ARCH)
        buildxArguments: --platform linux/$(ARCH) --output "type=image,push=false"
