name: ci

on:
    push:
        branches: experiment/v13
        paths-ignore:
            - '**/README.md'
            - 'infra/**'

    workflow_dispatch:

jobs:
    CI:
        name: Running CI to build / push docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to GitLab
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: darklight147
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ghcr.io/game-linter/discord-music-master:latest
                      ghcr.io/game-linter/discord-music-master:${{ github.sha }}
