name: ci

on:
    push:
        branches: [oop, master]
        paths-ignore:
          - '**/README.md'
    pull_request:
        branches: master

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to GitLab
              uses: docker/login-action@v1
              with:
                  registry: registry.gitlab.com
                  username: ${{ secrets.GITLAB_USERNAME }}
                  password: ${{ secrets.GITLAB_PASSWORD }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: registry.gitlab.com/darklight147/discord-music-master:latest

    CD:
        name: Deploy to production server
        needs: CI
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using pem file
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/ubuntu/workspace/discord-music-bot
                      sudo docker-compose down
                      sudo docker system prune -af
                      sudo docker-compose up -d
