name: ci

on:
    push:
        branches: [oop, master]
    pull_request:
        branches: master

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Packages Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: false
                  tags: darklight147/docker-music:latest
    CD:
        needs: CI
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/ubuntu/Discord-Music-Master
                      git pull origin master
                      docker rm $(docker stop $(docker ps -a -q --filter ancestor=darklight147/discord-music:latest --format="{{.ID}}"))
                      docker build -t darklight147/discord-music:latest .
                      docker run  -d — restart unless-stopped --env-file ./.env darklight147/discord-music:latest
