name: ci

on:
    push:
        branches: [oop, master]
    pull_request:
        branches: master

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to GitLab
              uses: docker/login-action@v1
              with:
                  registry: registry.gitlab.com
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.GITLAB_PASSWORD }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: registry.gitlab.com/darklight147/discord-music-master:latest

    CD:
        needs: CI
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/ubuntu/Discord-Music-Master
                      git pull origin master
                      docker pull registry.gitlab.com/darklight147/discord-music-master:latest
                      docker rm $(docker stop $(docker ps -a -q --filter ancestor=registry.gitlab.com/darklight147/discord-music-master:latest --format="{{.ID}}"))
                      docker run -d --env-file ./.env registry.gitlab.com/darklight147/discord-music-master:latest
